# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(max_length=400)),
                ('street_address', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('zip', models.CharField(max_length=100, null=True)),
                ('cc_number', models.CharField(max_length=200)),
                ('cc_exp_date', models.BooleanField(default=False)),
                ('cc_security_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=400)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperProducesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=400)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=400)),
                ('product_description', models.CharField(max_length=200)),
                ('price', models.CharField(default='', max_length=100)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('release_date', models.DateTimeField(max_length=200)),
                ('stock', models.BigIntegerField()),
                ('developer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Developer')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField(max_length=500)),
                ('review_date_time', models.DateTimeField(auto_now_add=True)),
                ('reivew_rating', models.DecimalField(decimal_places=1, max_digits=3, max_length=40)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Merchant')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_content', models.TextField(max_length=500)),
                ('ticket_date_time', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=50)),
                ('payment_method', models.CharField(max_length=40)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Merchant')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Product')),
            ],
        ),
        migrations.AddField(
            model_name='developerproducesproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Product'),
        ),
    ]
