# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.BigIntegerField(),
        ),
    ]
