# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20171127_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activation_key', models.CharField(max_length=200)),
                ('customer_name', models.TextField(max_length=400)),
                ('street_address', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('zip', models.CharField(max_length=100, null=True)),
                ('cc_number', models.CharField(max_length=200)),
                ('cc_exp_date', models.BooleanField(default=False)),
                ('cc_security_code', models.CharField(max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Developers',
            new_name='Developer',
        ),
        migrations.RenameModel(
            old_name='DevelopersProducesProducts',
            new_name='DeveloperProducesProduct',
        ),
        migrations.RenameModel(
            old_name='Merchants',
            new_name='Merchant',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='SupportTickets',
            new_name='SupportTicket',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Customer'),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
