# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20171128_0209'),
        ('data', '0006_remove_customer_customer'),
    ]

    operations = [
    ]
